    # Normal
  - [  0,   0,   0]  # Black
  - [128,   0,   0]  # Red
  - [  0, 128,   0]  # Green
  - [128, 128,   0]  # Brown/yellow
  - [  0,   0, 128]  # Blue
  - [128,   0, 128]  # Magenta
  - [  0, 128, 128]  # Cyan
  - [192, 192, 192]  # Gray

    # Bright
  - [128, 128, 128]  # Darkgray
  - [255,   0,   0]  # Red
  - [  0, 255,   0]  # Green
  - [255, 255,   0]  # Yellow
  - [  0,   0, 255]  # Blue
  - [255,   0, 255]  # Magenta
  - [  0, 255, 255]  # Cyan
  - [255, 255, 255]  # White
